version: '3.2'

services:

  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:7.3-fpm
    volumes:
      - ./public:/var/www

  db:
    image: mysql:5.7
    volumes: 
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  adminer:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - "8080:8080"
  
volumes:
  mysql_data: